### ISSUE TITLE
What's up with 0021.txt?

### ISSUE THREAD

**Issue by SeanStar** [projectpokemon/Pokemon-Black-White-Story-Translation-Files#5]
Is it just me? Looks messed up from here.. 
Anyone else see it?

http://github.com/projectpokemon/Pokemon-Black-White-Story-Translation-Files/tree/master/0000/0021.txt

**Comment by soneek** [comment]
Fixed

**Comment by SeanStar** [comment]
Alright, cool.

**Comment by kaarosu** [comment]
Yeah I'll just use yours in a later merge, not exactly sure what happened with that.

**Comment by SeanStar** [comment]
I think it may have something to do with a binary for some reason?.. Doesn't matter though, soneek's should fix it.
